[[Libgcrypt]]
arch = "aarch64"
git-tree-sha1 = "2f9a6c3f8e4d90b255acbaa526f01babe5c57cba"
os = "macos"

    [[Libgcrypt.download]]
    sha256 = "005bb42e47c49ff2faec19e052d0d1e2ad498412811f70810bdc4e4446f05d1e"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.aarch64-apple-darwin.tar.gz"
[[Libgcrypt]]
arch = "aarch64"
git-tree-sha1 = "55887a13803215639a3613512e652d858653c42b"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "7c4c499bd9ed87041bd4e301c4980a6e4d414e016e83d5857db6418d7545d46d"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.aarch64-linux-gnu.tar.gz"
[[Libgcrypt]]
arch = "aarch64"
git-tree-sha1 = "b8fd84e23c2e162afd374480c482fe09177ad5ac"
libc = "musl"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "3370f433b7713fa27e9aa1bbadaac39995b4194306a0918fccaf7ddf784fac1f"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.aarch64-linux-musl.tar.gz"
[[Libgcrypt]]
arch = "aarch64"
git-tree-sha1 = "df3ca610171c2c769186a82a5fcc0da9ea296cf4"
os = "freebsd"

    [[Libgcrypt.download]]
    sha256 = "b1c84db2cc3d33f4d3e30eea89b4a30d15869ef82cf7c37c3a1df19d82e2a121"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.aarch64-unknown-freebsd.tar.gz"
[[Libgcrypt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4471c44114ccc8adca85aa7b99b55b05890c7130"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "36e71d70b2c61fd7556dc9a6369d631b7741fbbe69c8a88ce61e8d18340368a3"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.armv6l-linux-gnueabihf.tar.gz"
[[Libgcrypt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6a991b2d634ddebeacb88a80a8b62624b285f439"
libc = "musl"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "847c509f7b9f672f769542f8550d3039bfb1c5f02ad287cb9df608c67584a1a8"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.armv6l-linux-musleabihf.tar.gz"
[[Libgcrypt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8b037bbe8182ca3cf1ab7a5ee922f0998361266f"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "09a62bc4dbdae723900a1195ec903141cf48768249beaf414afdc7e1d86c8d44"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.armv7l-linux-gnueabihf.tar.gz"
[[Libgcrypt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "09ca13db36b9ac2e690b72a309b6f9ea632e8e34"
libc = "musl"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "59f42e6bbe415e46a3dba10b733fc2dec805baac4e5e8d09956ea37c0f3f0822"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.armv7l-linux-musleabihf.tar.gz"
[[Libgcrypt]]
arch = "i686"
git-tree-sha1 = "82ac83945886b5f57fa5000e705d93c7dc05123a"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "45fcb38525fa73fa3d45f3a878bb15717cefc9e0ebad52c20fbbbf7bd77df5f6"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.i686-linux-gnu.tar.gz"
[[Libgcrypt]]
arch = "i686"
git-tree-sha1 = "6f1ced9a48695321722bc9977f8803329d51cd74"
libc = "musl"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "7615fcac4d8576665842c078dea21ff97f7c0d7ec09100753ccb8f470612787a"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.i686-linux-musl.tar.gz"
[[Libgcrypt]]
arch = "i686"
git-tree-sha1 = "fab1da6d38908c3cf2ce012a3578a6d28a1be9df"
os = "windows"

    [[Libgcrypt.download]]
    sha256 = "83b77cf1f1b8d87828e722769f24ab912eb6fb6ac486a143c9d4a80b3b3302ee"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.i686-w64-mingw32.tar.gz"
[[Libgcrypt]]
arch = "powerpc64le"
git-tree-sha1 = "c20d33e2ba1c1f2598c40f6fc3ad9af74b40d63f"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "97eb54d494444c53e20b3d23869ac4fc49ffbd67694d3b29229ec9ba87896d65"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.powerpc64le-linux-gnu.tar.gz"
[[Libgcrypt]]
arch = "riscv64"
git-tree-sha1 = "cfb79fd68654a96e678671b86266f15f7e32a276"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "c13ebda25d035faf38f9301e006e322b0aadd8e9a8bd7f7a9277b8cded463081"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.riscv64-linux-gnu.tar.gz"
[[Libgcrypt]]
arch = "x86_64"
git-tree-sha1 = "b6bea33489c2ae39b53d9cd20553500f052782f6"
os = "macos"

    [[Libgcrypt.download]]
    sha256 = "6974cf98e4fd7835a00b6212a0036f92368ae7ae49b840b60503179f8c445570"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.x86_64-apple-darwin.tar.gz"
[[Libgcrypt]]
arch = "x86_64"
git-tree-sha1 = "30c2be46c998ba228faea3625c2bf2413959b99f"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "e320d8c386d7db2792431819c6b8f691fc152a4623204133b55aa6ec3bce963c"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.x86_64-linux-gnu.tar.gz"
[[Libgcrypt]]
arch = "x86_64"
git-tree-sha1 = "a7fda14d3ba3ee48e0ea91a82a07514625cc3e5b"
libc = "musl"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "c4f98e816e587c785a370b1cc8d17fb6be91bfce624c1f354b377da82d920602"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.x86_64-linux-musl.tar.gz"
[[Libgcrypt]]
arch = "x86_64"
git-tree-sha1 = "afe2ccd282e6bb41beffb43521f90b0106cfb757"
os = "freebsd"

    [[Libgcrypt.download]]
    sha256 = "f312ea0c75340a99e501ca243563ae64cc2a3dc18a37b9cb6b32aa87610fd329"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.x86_64-unknown-freebsd.tar.gz"
[[Libgcrypt]]
arch = "x86_64"
git-tree-sha1 = "fb40c1b0cb1226d64918a43fdd7713383b258c4d"
os = "windows"

    [[Libgcrypt.download]]
    sha256 = "f2cba32e1cb76ab5b72a74adcda267c3a186a52ca42d45640bed339409a1c36b"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.12.1+0/Libgcrypt.v1.12.1.x86_64-w64-mingw32.tar.gz"
